name: Flutter CI

on:
  push:
    branches:
      - main  # Run CI when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Run CI for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'  # Ensure you specify a valid Flutter version
        channel: 'stable'  # Ensure the channel is specified correctly

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: flutter pub get

    # Step 4: Analyze Code
    - name: Analyze Code
      run: flutter analyze

    # Step 5: Run Tests
    - name: Run Tests
      run: flutter test
